accounts/urls.py
# from django.urls import path
# from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include, url
from .views import Profile

app_name = "accounts"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('username_change/', views.username_change, name="username_change"),
    path('password_change/', views.password_change, name="password_change"),
    path('profile/', Profile.as_view(), name="profile"),
         ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
]

photo/urls.py
from django.urls import path
from .views import PhotoList, PhotoDelete, PhotoDetail, PhotoUpdate, PhotoCreate, PhotoLike, PhotoBookmark, PhotoLikeList, PhotoBookmarkList, PhotoMyList, comment_create_photo, comment_modify_photo, comment_delete_photo, PhotoUp, PhotoDown
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "photo"
urlpatterns = [
    path("mylist/", PhotoMyList.as_view(), name="mylist"),
    path("create/", PhotoCreate.as_view(), name='create'),
    path("like/<int:photo_id>/", PhotoLike.as_view(), name='like'),
    path("bookmark/<int:photo_id>/", PhotoBookmark.as_view(), name='bookmark'),
    path("delete/<int:pk>/", PhotoDelete.as_view(), name='delete'),
    path("update/<int:pk>/", PhotoUpdate.as_view(), name='update'),
    path("detail/<int:pk>/", PhotoDetail.as_view(), name='detail'),
    path("like/", PhotoLikeList.as_view(), name="like_list"),
    path("bookmark/", PhotoBookmarkList.as_view(), name="bookmark_list"),
    path("up/<int:photo_id>/", PhotoUp.as_view(), name="up"),
    path("down/<int:photo_id>/", PhotoDown.as_view(), name="down"),
    path('detail/<int:photo_id>/comment_create/', views.comment_create_photo, name='comment_create'),
    path('detail/<int:comment_id>/comment_modify/', views.comment_modify_photo, name='comment_modify'),
    path('detail/<int:comment_id>/comment_delete/', views.comment_delete_photo, name='comment_delete'),
    path('search/', views.SearchFormView, name='search'),
    path('', PhotoList.as_view(), name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import ImageField
from django.urls import reverse
from PIL import Image

class Photo(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'user')
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='timeline_photo/%Y/%m/%d', default='/media/profile_pics/ha.jpg')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    like = models.ManyToManyField(User, related_name='like_post', blank=True)
    up = models.ManyToManyField(User, related_name='up_post', blank=True)
    down = models.ManyToManyField(User, related_name='down_post', blank=True)
    bookmark = models.ManyToManyField(User, related_name='bookmark_post', blank=True)
    
    def __str__(self):
        return "text : " +self.text
    
    class Meta:
        ordering = ['-created']
        
    def get_absolute_url(self):
        return reverse('photo:detail', args=[self.id])
    
class Comment(models.Model):
    #댓글 기능 구현을 위해 <작성자, 댓글 내용, 댓글 생성일, 댓글 수정일, 해당 사진>
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    photo = models.ForeignKey(Photo, null=True, blank=True, on_delete=models.CASCADE)

photo/forms.py
from django import forms
from photo.models import Photo, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

photo/views.py
# from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView, FormView
from django.views.generic.detail import DetailView
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse
from django.utils import timezone
from django.db.models import Q
from .models import Photo, Comment
from .forms import CommentForm
from flask import request
from django.http import HttpResponseRedirect
from django.contrib import messages
# from .forms import CommentForm, PostSearchForm
# Create your views here.

class PhotoList(ListView):
    model = Photo
    template_name_suffix = '_list'

class PhotoCreate(CreateView):
    model = Photo
    fields = ['text', 'image']
    template_name_suffix = '_create'
    success_url = '/'
    
    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form': form})
    
class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['text', 'image']
    template_name_suffix = '_update'
    # success_url = '/'
    
    def dispatch(self, request, *args, **kwargs) :
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '수정할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        
        else:
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)

class PhotoDelete(DeleteView):
    model = Photo
    template_name_suffix = '_delete'
    success_url = '/'
    
    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '삭제할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else:
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)

class PhotoDetail(DetailView):
    model = Photo
    template_name_suffix = '_detail'

class PhotoUp(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.up.all():
                    photo.up.remove(user)
                else:
                    photo.up.add(user)
                    
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)
        
class PhotoDown(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.down.all():
                    photo.down.remove(user)
                else:
                    photo.down.add(user)
                    
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)
    
class PhotoLike(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.like.all():
                    photo.like.remove(user)
                else:
                    photo.like.add(user)
                    
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)
        
class PhotoBookmark(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect('/accounts/login')
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.bookmark.all():
                    photo.bookmark.remove(user)
                else:
                    photo.bookmark.add(user)
            return HttpResponseRedirect('/')
        
class PhotoLikeList(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, '로그인을 먼저 하세요')
            return HttpResponseRedirect('/')
        return super(PhotoLikeList, self).dispatch(request, *args, **kwargs)
    
    def get_queryset(self):
        user = self.request.user
        queryset = user.like_post.all()
        return queryset
    
class PhotoBookmarkList(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, '로그인을 먼저 하세요')
            return HttpResponseRedirect('/')
        return super(PhotoBookmarkList, self).dispatch(request, *args, **kwargs)
    
    def get_queryset(self):
        user = self.request.user
        queryset = user.bookmark_post.all()
        return queryset
    
class PhotoMyList(ListView):
    model = Photo
    template_name = 'photo/photo_mylist.html'
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, '로그인을 먼저 하세요')
            return HttpResponseRedirect('/')
        return super(PhotoMyList, self).dispatch(request, *args, **kwargs)
    
    
@login_required(login_url='accounts:login')
def comment_create_photo(request, photo_id):
    photo = get_object_or_404(Photo, pk=photo_id)
    if request.method == "POST":
        form = CommentForm(request.POST) #폼 불러오기
        if form.is_valid():
            comment = form.save(commit=False) #폼 객체를 통해 데이터 저장, 추가적인 데이터 저장 위해 DB에 바로 반영 X
            comment.author = request.user #댓글 작성자 <= 현재 유저 대입
            comment.create_date = timezone.now() #댓글 작성 시간 <= 현재 시간 대입
            comment.photo = photo #댓글이 달린 사진 <= 지금 사진
            comment.save() #최종적으로 저장
            return redirect('photo:detail', pk=photo.id)
            # return HttpResponseRedirect('/')
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'photo/comment_form.html', context)

@login_required(login_url='accounts:login')
def comment_modify_photo(request, comment_id):
    """
    photo 질문댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('photo:detail', pk=comment.photo.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('photo:detail', pk=comment.photo.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'photo/comment_form.html', context)

@login_required(login_url='accounts:login')
def comment_delete_photo(request, comment_id):
    """
    photo 질문댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('photo:detail', pk=comment.photo.id)
    else:
        comment.delete()
    return redirect('photo:detail', pk=comment.photo.id)


def SearchFormView(request):
    content_list = Photo.objects.all() #모든 게시글을 가져오기
    search_word = request.GET.get('search_word','') #검색어 값이 있으면 가져오고, 없으면 빈 문자열을 넣음
    
    if(search_word == ''):
        post_list = []
        
    else:
        post_list = content_list.filter(Q(text__icontains=search_word)).distinct()
        #검색어 값과 일치하는 부분이 있는 게시글만 따로 저장, Q객체 사용

    context = {}
    context['search_term'] = search_word
    context['object_list'] = post_list
    #잘 집어넣어서 넘겨주기

    return render(request, 'photo/search.html', context)

photo/templates/photo/photo_create.html
{% extends 'base.html' %}
{% block content %}
<style>
    textarea{
        color: black;
        width: 100%;
    }
    
    .col-12{
        padding-top: 5.5em;
    }
    .btn{
        color: #FFF9F9;
        background-color: #BAABDA;
    }
    .btn:hover{
        color: #FFF9F9;
    }
</style>
<div class="row">
   <div class="col"></div> 
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post" enctype="multipart/form-data" style="color: black;">
            {% csrf_token %}
            
            {{form.as_p}}
            <input type="submit" value="Create" class="btn">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_delete.html
{% extends 'base.html' %}
{% block content %}

<style>
    body{
        padding-top: 5.5em;
    }
    .btn{
        color: #FFF9F9;
        background-color: #BAABDA;
    }
    .btn:hover{
        color: #FFF9F9;
    }
    .alert{
        color: #FFF9F9;
        background-color: #BAABDA;
    }
</style>

<div class="alert" rol="alert">
    진짜로 {{object}} 를 지울건가요?
</div>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn">
</form>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<style>
    .col-7{
        padding-top: 5.5em;   
    }
    .no_comment{
        padding: 10px;
    }
    .comment{
        padding: 10px;
    }
    .list-group{
        border-radius: 0;
    }
    .list-group-item{
        border: 0;
    }
    .card-link{
        color: #BAABDA;
    }
    .card-link:hover{
        color: #7C3E66;
    }
    b{
        padding-left: 10px;
    }
    a{
        color: #7C3E66;
    }
    a:hover{
        color: #7C3E66;
    }
    #comment_padding{
        padding-left: 10px;
    }
</style>
<div class="row">
        <div class="col"></div>
        <div class="col-7">
            <div class="card" style="margin-bottom: 2em">
                <img src= "{{ object.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <a href="{% url 'photo:up' object.id %}"
                       class="float-left btn-up {% if user in object.up.all %} active {% endif %}"></a>
                    {% if object.up.all.count %}
                    <span class="float-left">
                        {{object.up.all.count}}
                    </span>
                    {% endif %}
                    <a href="{% url 'photo:down' object.id %}" class="float-right btn-down {% if user in object.down.all %} active {% endif %}"></a>
                    {% if object.down.all.count %}
                    <span class="float-right">
                        {{object.down.all.count}}
                    </span>
                    {% endif %}
                    <br><br><br>
                    <p class="card-text"><strong>{{ object.author }}</strong></p>
                    <p class="card-text">{{ object.text|linebreaks }}</p>
                </div>
                <ul class="list-group"> 
                    <li class="list-group-item">생성일 : {{ object.created }}</li>
                    {% if object.updated and object.updated != object.created %}
                    <li class="list-group-item">수정일 : {{ object.updated }}</li>
                    {% else %}
                    <li class="list-group-item">-</li>
                    {% endif %}

                    <p class="card-text">
                       {% if photo.comment_set.count > 0 %}
                            <div>
                            {% for comment in photo.comment_set.all %}  <!-- 등록한 댓글을 출력 -->
                                <div class="comment py-2 text-muted">  <!-- 댓글 각각에 comment 스타일 지정 -->
                                    <span><b>{{ comment.author }}</b></span>
                                    <span style="white-space: pre-line;" id="comment_padding">{{ comment.content }}</span>
                                    <span id="comment_each">
                                        {% if comment.modify_date %}
                                        (수정: {{ comment.modify_date }})
                                        {% else %}
                                        ({{ comment.create_date }})
                                        {% endif %}
                                    </span>
                                    {% if request.user == comment.author %}
                                    <a href="{% url 'photo:comment_modify' comment.id  %}" class="small">수정</a>,
                                    <a href="{% url 'photo:comment_delete' comment.id  %}" class="small delete" 
                                       data-uri="{% url 'photo:comment_delete' comment.id  %}">삭제</a>
                                    {% endif %}
                                </div>
                            {% endfor %}
                            </div>
                        {% else %}
                        <div class="no_comment">
                            <p class="card-text">
                            <b>댓글이 없습니다.</b>
                            </p>
                        </div>
                        {% endif %}
                            <div>
                </div>
                </ul>
                <div class="card-body">
                    {% if user == object.author %}
                    <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                    <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
                    {% endif %}
                    <a href="{% url 'photo:comment_create' object.id %}" class="card-link">댓글달기</a>
                </div>
            </div>
        </div>
    <div class="col"></div>
</div>

{% endblock %}

photo/templates/photo/photo_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}

<style>
    .col-6{
        padding-top: 3em;
        display: flex;
        flex-direction: column;
    }
    .row{
        padding-top: 38px;
        justify-content: center;
    }
    .text{
        display: flex;
        justify-content: center;
    }
    .text_m{
        margin: 0;
    }
    .card-link{
        color: #BAABDA;
    }
    .card-link:hover{
        color: #7C3E66;
    }
</style>

<div class='container'>
    <div class="row">
        <div class="col"></div>
        <div class="col-6">
            {% if object_list %}
                {% for object in object_list %}
                <div class="card" style="margin-bottom: 2em;">
                    <img src="{{ object.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'photo:like' object.id %}" class="float-left btn-like {% if user in object.like.all %} active {% endif %}"></a>
                        {% if object.like.all.count %}
                        <span class="float-left">
                            {{object.like.all.count}}
                        </span>
                        {% endif %}
                        <a href="{% url 'photo:bookmark' object.id %}" class="float-right btn-bookmark {% if user in object.bookmark.all %} active {% endif %}"></a>
                        <br><br><br>
                        <p class="card-title"> <strong>{{ object.author }}</strong></p>
                        <p class="card-text">{{ object.text|linebreaks }}</p>
                    </div>
                    <div class="card-body">
                        <a href="{% url 'photo:detail' object.id %}" class="card-link">댓글({{ object.comment_set.count }})</a>
                        {% if user == object.author %}
                        <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                        <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <div class="text">
                    <b><i>글이 없습니다.</i></b>
                </div>
            {% endif %}
            
            
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

photo/templates/photo/photo_mylist.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<style>
    .row{
        padding-top: 3em;
        justify-content: center;
    }
    .ob_body{
        padding: 2em;
        padding-top: 0px;
    }
    .card-body{
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 1.25em 0.5em;
    }
    .card img{
        height: 200px;
        object-fit:cover;
    }
    .profile{
        margin: 10px;
        width: 125px;
        height: 125px;
        background-image: url("/media/profile_pics/duck.jpg");
        background-size:cover;
        background-position:center;
        border-radius: 50%;
    }
    .card{
        background-color: #FFF9F9;
            border: 0;
            border-radius: 0;
    }
    .photo_scr{
        padding: 10px;
    }
    .photo_img{
        background-color: white;
    }
    #heart{
        color: black;
    }
    .heart_count{
        display: flex;
        justify-content: flex-end;
    }
    .photo{
        background-clip: border-box;
        border: 1px solid rgba(0,0,0,.125);
        border-radius: 0.25rem;
        height: 30em;
    }
    
</style>

<div class="row">
    <div class="col-md-12">
        <div id="mdb-lightbox-ui"></div>
        <div class="mdb-lightbox no-margin">
            <div class="row">      
                <div class="card" style="width: 30rem;">
                  <div class="card-body">
                        <a href="{% url 'accounts:profile' %}"><div class="profile" title="클릭하면 프로필 변경 페이지로 이동합니다"></div></a>
                    <h5 class="card-title">{{ user }}</h5>
                    <a href="{% url 'accounts:username_change' %}" style="color: #7C3E66;">ID 변경</a>
                    <a href="{% url 'accounts:password_change' %}" style="color: #7C3E66;">비밀번호 변경</a>
                  </div>
                </div>            
            </div>      
            <div class="row">
                {% for object in object_list %}
                {% if object.author == request.user %}
                <div class="ob_body">
                    <figure class="ob_list">
                        <div style="width : 19rem;" class="photo">
                            <div class="photo_img card-body">
                                <a href="{% url 'photo:detail' object.id %}" class="card-link"><img src="{{object.image.url}}" style="height: 18rem; object-fit: scale-down;"class="card-img-top" alt="..."></a>
                            </div>
                            <div class="photo_scr">
                                <p class="card-text">{{ object.text|truncatechars:23}} </p>
                                <p class="card-text">{{ object.created }}, {{ object.comment_set.count }}개의 댓글</p>
                                <div class="heart_count">
                                    <span id="heart" class="material-symbols-outlined">heart_plus</span>
                                    <span class="float-left">
                                        {{object.like.all.count}}
                                    </span>
                                </div>
                            </div>
                        </div>
                    </figure>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="col"></div>
    </div>
</div>

{% endblock%}

photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block content %}
<style>
    .row{
        padding-top: 5.5em;
    }
    
    textarea{
        color: black;
        width: 100%;
    }
    .btn{
        color: #FFF9F9;
        background-color: #BAABDA;
    }
    .btn:hover{
        color: #FFF9F9;
    }
</style>
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Update" class="btn">
        </form>
    </div>
    <div class="col"></div>
</div>

{% endblock %}